export const ADD_INREDIENTS = "ADD_INGRIDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PERCHASE_BURGER_START = "PERCHASE_BURGER_START";
export const PERCHASE_BURGER_SUCCESS = "PERCHASE_BURGER_SUCCESS";
export const PERCHASE_BURGER_FAIL = "PERCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
